### ISSUE TITLE
passwords.cmd

### ISSUE THREAD

**Issue by Papotito123** [erwan2212/NTHASH-FPC#1]
Hello:
This tools looks some intimidating for average joe like me, but I use mimkatz and I'm working to get in the pace to understand.
But has some things that run more easy.

I  edit password.lst to add my users passwords,

I run passwords.cmd but that's what I got:

C:\Users\TESTACCOUNT\Downloads\NTHASH-FPC\NTHASH-FPC-master\NTHASH-FPC-master>passwords.cmd
 = password

Seems just stuck in password.lst first line.

Any general info about how features will be good.

Any info much appreciated.

Thanks.

**Comment by erwan2212** [comment]
Hi,

Thanks for the feedback.
There was a bug in passwords.cmd.
Download nthash.zip again.

Command line should be : passwords.cmd 8846F7EAEE8FB117AD06BDD830B7586C .
Output should be: 8846F7EAEE8FB117AD06BDD830B7586C = password

The patch will generate the ntlm hash for each clear text password in
passwords.lst and will compare it to the supplied ntlm hash.

Regards,
Erwan

Le ven. 27 mars 2020 à 05:08, Papotito123 <notifications@github.com> a
écrit :

**Comment by Papotito123** [comment]
Hello:
Thanks for responding.
Now works ok.

Thanks.
