### ISSUE TITLE
/dpapimk Win 10 2004H1

### ISSUE THREAD

**Issue by Papotito123** [erwan2212/NTHASH-FPC#12]
Hello:
You mention to use /dpapimk /symbol in other post/issue.

Well I tested in WIn 10 2004H1.

![Papotito123_dpapimk_Win 10 2004H1](https://user-images.githubusercontent.com/53058383/96396091-4ecfb800-1194-11eb-8b6b-852049ea4e5d.jpg)

You will see \Protect folder looks empty even recovers a GUID with matching pairs.
But this guid is not the one needed to recover Chrome logins.

Update:
But files are here even doesn't showing with Hidden Items setting.
Via cmd or other tools,  the files can be copying/seeing.

**Comment by erwan2212** [comment]
Need to review dpapimk on win 10 2004.
The LUID you are getting 2d967 needs to be checked (which user?).

Have you tried with /dpapimk /symbol.

**Comment by Papotito123** [comment]
Hello:
In the DPAPI.txt  there's the command  I ran,  the output , and in the info.txt there's the info I know.
You can see the guid are not the same.

As for guid files are not showing,is part of the security measures in Win 2004 to visually hide critic folders/files.Still can be grabbed.

As a side-note for Win 2004,most of tools can't grab LSA secrets Q&A.Nor mimi, nor lazagne or others .Except 1 tool from nirsoft.

**Comment by Papotito123** [comment]
Hello:
Is Win 10 2004H1 MicrosoftAccount user.

Now used nthash erwan2212 windows 2004 support f4487b1

I ran /dpapimk /symbol  again, and now gives 3 guid-mkey/sha1 and are good(mimi sekurlsa::dpapi verified).
Last time only gave 2 guids and none was the guid needed for chrome logins.

Thanks again.

**Comment by Papotito123** [comment]
Hello:
My OS did some updates.
So I ran /dpapimk /symbol again .And as same as last time it retrieved the dpapi keys.

Thanks
