### ISSUE TITLE
chrome.exe use

### ISSUE THREAD

**Issue by Papotito123** [erwan2212/NTHASH-FPC#14]
Hello:
I tested chrome.exe in PROBANDO MicrosoftAccount user.
I don't know how to, but I just run and give this:

C:\Users\PROBANDO\Downloads\NTHASH-FPC-mas\NTHASH-FPC-master\chrome>chrome.exe
path:C:\Users\PROBANDO\AppData\Local\Google\Chrome\User Data\Default
db:C:\Users\PROBANDO\AppData\Local\Google\Chrome\User Data\Default\login data.db
os_crypt:encrypted_key:F67xzxxxxxxxxxxxxxxxxxxxxxxxx6EA
Exception ESQLite3Exception in module chrome.exe at 00046EA2.
Unable to load sqlite3.dll - The specified module could not be found.

I recognized that  , os_crypt:encrypted_key:F67xzxxxxxxxxxxxxxxxxxxxxxxxx6EA  , is the Local State AES key needed to decrypt Chome logins.

So, I looked inside nthash folder and saw sqlite3-64.dll/sqlite3.dll files and copied to extracted chrome.zip.
And Chrome Logins (new encryption) are decrypted automatically. Cool.
And I'm doing in this in PROBANDO MicrosoftAccount user. 

C:\Users\PROBANDO\Downloads\NTHASH-FPC-mas\NTHASH-FPC-master\chrome>chrome.exe
path:C:\Users\PROBANDO\AppData\Local\Google\Chrome\User Data\Default
db:C:\Users\PROBANDO\AppData\Local\Google\Chrome\User Data\Default\login data.db
os_crypt:encrypted_key:F67xzxxxxxxxxxxxxxxxxxxxxxxxx6EA
https://login.live.com/login.srf;myemail@hotmail.com;mypassword;*

There's other switches ?
This make process more fast.Cool.

**Comment by erwan2212** [comment]
Chrome.exe was a special request I got.
It is build against nthash chrome module so it does the same as nthash /chrome : no extra switches.

If you wish to have a dedicated standalone exe for one particular nhash feature : I can easily make it happen.

**Comment by Papotito123** [comment]
Hello:
Don't worry.
I suspected that is compact module.

Much thanks

**Comment by erwan2212** [comment]
Chrome.exe is a standalone tool
