### ISSUE TITLE
/inject and nplogonnotify hook

### ISSUE THREAD

**Issue by Papotito123** [erwan2212/NTHASH-FPC#6]
Hello:
Long time.
So much things are happen.

Regarding nplogonnotify feature, this only works in DC environment?

I tested in my compuiter. It copies nplogonnotify.dll and made the 2 registry entries.
But I have to choose my user name and enter password to login.

Or I am doing wrong?

Thanks for keep the works.

**Comment by erwan2212** [comment]
Hi Papito123,

It will work in any (x64) environement.
Once the dll is copied in system32 and registered (in the registry) by setup.cmd, you are good to go.

It will "only" log/snif username/password in c:\nplogon.txt - nothing else.

Regards,
Erwan

**Comment by Papotito123** [comment]
Hello:
Thanks for explanation.
I thought it catches user login and "save it" to perform auto login, like konboot.
My bad.

Seems more like memssp feature so user have to re-login ,to login info be catched.

I will seek for the .txt .

Thanks.

**Comment by Papotito123** [comment]
Hello:
I see c:\nplogon.txt and has my login.
Even without unlocking lsass.exe or having wdigest Enabled.

You are diving into deep things.
I'm seeing you are making some pretty things with this tool.
I'm testing.

So much thanks.

**Comment by Papotito123** [comment]
Hello;
I installed Win10 2004 19041.450 x64(August 2020) to test some tools.

The module nplogonnotify worked well.
At first login after applied , it catched "_TBAL_{68EDDCF5-0AEB-4C28-A770-AF5302ECA3C9}".
At second login it catched my user password.

Just to inform.

**Comment by Papotito123** [comment]
Hello:
Just closing.
