### ISSUE TITLE
/inject and MsvpPasswordValidate hook

### ISSUE THREAD

**Issue by Papotito123** [erwan2212/NTHASH-FPC#7]
Hello:
I tested to inject hook MsvpPasswordValidate and did good.
I could login with other password than mine.

So then I tried doing the eject hook to disable the feature and gives this:

C:\Users\TESTACCOUNT\Downloads\NTHASH-FPC-master(18AGO2020)\NTHASH-FPC-master\NTHASH-FPC-master\NTHASH>nthash-win64.exe /enumproc | findstr lsass
824     lsass.exe       NT AUTHORITY\SYSTEM

C:\Users\TESTACCOUNT\Downloads\NTHASH-FPC-master(18AGO2020)\NTHASH-FPC-master\NTHASH-FPC-master\NTHASH>NTHASH-win64.exe /eject /pid:824 /binary:C:\Users\TESTACCOUNT\Downloads\NTHASH-FPC-master(18AGO2020)\NTHASH-FPC-master\NTHASH-FPC-master\NTHASH\hook-win64.dll
NTHASH 1.8 x64 by erwan2212@gmail.com
_EnumMod not ok

So I checked if is really hooked:
C:\Users\TESTACCOUNT\Downloads\NTHASH-FPC-master(18AGO2020)\NTHASH-FPC-master\NTHASH-FPC-master\NTHASH>NTHASH-win64.exe /enummod /pid:824 | findstr hook
110000000 hook-win64.dll

My Avast is turned OFF.

Thanks for any info.

**Comment by erwan2212** [comment]
When using eject, provide the filename not the full path.
binary=hook-win64.dll.

Let me know if it works for you.

**Comment by Papotito123** [comment]
Hello:
Ok.My bad.

I will try later.

So much thanks.

**Comment by Papotito123** [comment]
Hello:
For MsvpPasswordValidate doing /eject  , this is output:

C:\Users\TESTACCOUNT\Downloads\NTHASH-FPC-master(18AGO2020)\NTHASH-FPC-master\NTHASH-FPC-master\NTHASH>nthash-win64.exe /enumproc | findstr lsass
844     lsass.exe       NT AUTHORITY\SYSTEM

C:\Users\TESTACCOUNT\Downloads\NTHASH-FPC-master(18AGO2020)\NTHASH-FPC-master\NTHASH-FPC-master\NTHASH>NTHASH-win64.exe /eject /pid:844 /binary:hook-win64.dll /verbose
NTHASH 1.8 x64 by erwan2212@gmail.com
_EnumMod not ok

C:\Users\TESTACCOUNT\Downloads\NTHASH-FPC-master(18AGO2020)\NTHASH-FPC-master\NTHASH-FPC-master\NTHASH>NTHASH-win64.exe /enummod /pid:844 | findstr hook

C:\Users\TESTACCOUNT\Downloads\NTHASH-FPC-master(18AGO2020)\NTHASH-FPC-master\NTHASH-FPC-master\NTHASH>NTHASH-win64.exe /enummod /pid:844 | findstr hook /verbose
FINDSTR: Cannot open /verbose
An unhandled exception occurred at $000000010003D0AA:
EInOutError: Disk Full
  $000000010003D0AA
  $00000001000081DA
  $000000010000BDB6
  $000000010001D8C3
  $000000010001E211
  $00007FFFAEDF7974
  $00007FFFAFFAA271

Same thing happens for MsvpPasswordValidateV2 hook-win64.dll.
Now I have 2 hook-win64.dll can't be ejected. And as I remembered , the PID for lsass.exe is different from last day.

I noticed something...
The PID given in NTHASH for lsass.exe (844) is assigned to VaultSvc(Credential Manager) in Services.But also is assigned to lsass.exe in Details. 
This should be right or not? right 

What to do?

**Comment by Papotito123** [comment]
Hello:
Other thing.
Wen I login today I tested inputing other password and doesn't get it and have  to use my pasword.
So maybe MsvpPasswordValidate is not working because it was ejected.
Also for  MsvpPasswordValidateV2 ,the log.txt timestamp says last accessed was ‎Yesterday, ‎August ‎18, ‎2020, ‏‎10:02:59 PM.This was the time I was trying to do /eject for ‎MsvpPasswordValidate and MsvpPasswordValidateV2.
So the ejecting process should be automatically or after a Restart/Shutdown?
Because I tried 4-5 times laast night.

Regarding log.txt it never output user hashes:

BEGIN
attach
MsvpPasswordValidate:1
BEGIN
attach
MsvpPasswordValidate:1

Update:
I tried to run MsvpPasswordValidate again and is not working.
I Restarted computer and I have to use my password, /inject and /eject and /enummod  | findstr hook doesn't show anything.

**Comment by erwan2212** [comment]
>NTHASH-win64.exe /eject /pid:844 /binary:hook-win64.dll /verbose
>NTHASH 1.8 x64 by erwan2212@gmail.com
>_EnumMod not ok

Means the injected module (hook-win64.dll) is not there.
I have changed the output now to 'module not found'.

>NTHASH-win64.exe /enummod /pid:844 | findstr hook

If not output, means again that the module is not found in pid 844.

About that, you can also simply run NTHASH-win64.exe /enummod /pid:844 and check if hook-win64.dll is there (usually on the last line).

>NTHASH-win64.exe /enummod /pid:844 | findstr hook /verbose
>FINDSTR: Cannot open /verbose

verbose is located at the wrong mark in this command line.
It should be NTHASH-win64.exe /enummod /pid:844 /verbose | findstr hook.
This is crashing the nthash output.

>The PID given in NTHASH for lsass.exe (844) is assigned to VaultSvc(Credential Manager) in Services.But also is assigned to >lsass.exe in Details.
>This should be right or not? right

This is right.

**Comment by erwan2212** [comment]
>Wen I login today I tested inputing other password and doesn't get it and have to use my pasword.
>So maybe MsvpPasswordValidate is not working because it was ejected.
>Also for MsvpPasswordValidateV2 ,the log.txt timestamp says last accessed was ‎Yesterday, ‎August ‎18, ‎2020, ‏‎10:02:59 PM.This >was the time I was trying to do /eject for ‎MsvpPasswordValidate and MsvpPasswordValidateV2.
>So the ejecting process should be automatically or after a Restart/Shutdown?
>Because I tried 4-5 times laast night.

Yes it looks like you had successfully ejected the module(s).
It will stay loaded until next reboot unless you eject it manually.

>Regarding log.txt it never output user hashes:
>BEGIN
>attach
>MsvpPasswordValidate:1

This is the output of my first hook which "only" allow the use of any password.

If you want to retrieve hashes, you need to inject MsvpPasswordValidateV2.
I confess this is confusing as the dll do have the same names between MsvpPasswordValidate (aka v1) and MsvpPasswordValidateV2.

Output of MsvpPasswordValidateV2 should look like below:
***************
LogonLevel:x
EncryptedNtOwfPassword:aabbccddeeff1122334455667788
LogonDomainName:xxx
UserName:xxx
Workstation:xxxx'


If you reboot, you need to inject it again as it does not survive a reboot.

**Comment by erwan2212** [comment]
Just to be sure : redownload msvpasswordvalidatev2 - looks like my github was not refreshed with latest version...
Same goes with nthash-win64.exe.

**Comment by Papotito123** [comment]
Hello:
Thanks for keep in touch.
Yeah.The hook dlls are the same and a bit confusing. Also I ran nplogon. And then tested msvpasswordvalidate and msvpasswordvalidatev2 one after another.

I'll try later.

**Comment by Papotito123** [comment]
Hello:
I was ready to ask a Dumb question , but I tried more.
I noticed that lsass.exe PID changes at OS Start/Restart.
After running msvpasswordvalidate or msvpasswordvalidatev2,it survives only doing a Signout and re-Login but not when doing a Restart. 
I ran msvpasswordvalidate and msvpasswordvalidatev2 and see the info in log.txt .
But I have to re-login .

So the "fake password trick" and grab "logged user hash" needs to do SignOut and re-Login. Am I right?

I thought that msvpasswordvalidate specific hook survives among Restarts.

NTHASH-win64.exe /dumphashes /syste works good as retrieves all accounts real hashes.

So ,msvpasswordvalidate and msvpasswordvalidatev2 looks to me , more as a pen-testing for remote login because to "benefit of password trick" and to "grab current logged user hash" a re-login is needed.

Any more explanation will be good.

For /eject command, the output is now to 'module not found'.
The output of MsvpPasswordValidateV2 is as should be.

Thanks again.

**Comment by erwan2212** [comment]
>I noticed that lsass.exe PID changes at OS Start/Restart.
>After running msvpasswordvalidate or msvpasswordvalidatev2,it survives only doing a Signout and re-Login but not when >doing a Restart.

Correct : lsass pid will change at every restart and hooks will not survicve a restart.

>So the "fake password trick" and grab "logged user hash" needs to do SignOut and re-Login. Am I right?

Any user who will sign in will be logged : signing in is therefore key for this trick.
This applies to a local user OR a remote user.

>I thought that msvpasswordvalidate specific hook survives among Restarts.

These hooks will not survive a system restart.

>So ,msvpasswordvalidate and msvpasswordvalidatev2 looks to me , more as a pen-testing for remote login because to "benefit >of password trick" and to "grab current logged user hash" a re-login is needed.

You are right : a login/sign in is needed as opposed to the other methods where passwords/hashes are either stored in the sam db or in memory.
Lets say it is a complementary way of grabing hashes next to the /logonpasswords and /wdigest method.

>Any more explanation will be good.

Let me know if clearer for you now.

Thanks a lot for your feedback and tests as always !

**Comment by Papotito123** [comment]
Hello:
Better than that , impossible. 
Yeah.These tools can be an aid for certain situations.

nplogon feature is serious.No need for widgest or to unlock lsass.exe .
I managed to modify setup.cmd to unsetup.cmd to delete nplogon dll and delete the created registries.Worked well.

Thanks for keeping up your work.
Thanks for keep in touch.

**Comment by Papotito123** [comment]
Hello:
Just closing.
